spring.application.name=team6_backend

# Database
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/inter?useSSL=false&serverTimezone=UTC}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# MyBatis
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=com.example.team6_backend.entity
mybatis.configuration.map-underscore-to-camel-case=true

# Rakuten Web Service
rakuten.application-id=${RAKUTEN_APPLICATION_ID:}
rakuten.application-secret=${RAKUTEN_APPLICATION_SECRET:}
rakuten.affiliate-id=${RAKUTEN_AFFILIATE_ID:}
rakuten.item-api-url=https://app.rakuten.co.jp/services/api/IchibaItem/Search/20220601
rakuten.genre-api-url=https://app.rakuten.co.jp/services/api/IchibaGenre/Search/20140222
