spring.application.name=team6_backend
# ?????
spring.datasource.url=jdbc:mysql://34.146.229.133/inter?useSSL=false&serverTimezone=UTC
spring.datasource.username=tios
spring.datasource.password=Chen36631489()
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# MyBatis ??
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=com.example.team6_backend.entity

rakuten.application-id=1022265988501327127
rakuten.application-secret=0ac0231b12c673522dee331f7b65b9f85505603f
rakuten.affiliate-id=4c284052.672b6c11.4c284053.a4401fb7
rakuten.item-api-url=https://app.rakuten.co.jp/services/api/IchibaItem/Search/20220601
rakuten.genre-api-url=https://app.rakuten.co.jp/services/api/IchibaGenre/Search/20140222
